name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Load .env file
        uses: natterstefan/action-next-env@v1
        with:
          path: ./
          environment: development

      - name: Set up pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Install vercel CLI
        run: pnpm add -g vercel@latest

      - name: Pull vercel environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project artifacts to vercel
        run: |
          vercel deploy --prebuilt \
            --env NEXT_PUBLIC_ENV=${{ env.NEXT_PUBLIC_ENV }} \
            --token=${{ secrets.VERCEL_TOKEN }}
